
version: "3.8"

services:
  web:
    build: .
    restart: always
    command: bash -c "cd src && python manage.py migrate && gunicorn intrip_backend.wsgi -b 0.0.0.0:8000 --workers 2 --log-level debug"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
