# Generated by Django 3.1.3 on 2020-11-08 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201108_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='claim_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claimants', to='api.wallet'),
        ),
    ]
