# Generated by Django 3.1.3 on 2020-11-08 17:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201108_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='from_wallet',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='to_wallet',
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='from_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='f_tickets', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='to_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='t_tickets', to='api.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated_at'),
        ),
    ]
