# Generated by Django 3.1.3 on 2020-11-08 20:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201108_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketclaimmapping',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ticketclaimmapping',
            name='employer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employer_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
